@startuml
title Система Управления Обращениями

left to right direction

actor Пользователь
actor Оператор

rectangle {
  usecase U1 as "Оценить качество\nответа"
  usecase U2 as "Создать обращение"
  usecase U3 as "Получить\nавтоматический ответ"
  usecase U4 as "Отследить статус\nобращения"
  usecase U5 as "Выбрать шаблон\nобращения"
  usecase U6 as "Запросить\nдополнительную\nинформацию"

  usecase O1 as "Обработать\nнерешенное\nобращение"
  usecase O2 as "Просмотреть\nисторию поиска\nсистемы"

  Пользователь -- U1
  Пользователь -- U2
  Пользователь -- U3
  Пользователь -- U4

  Оператор -- O1

  U2 ..> U5 : <<include>>
  U3 <.. U6 : <<extend>>
  O1 ..> O2 : <<include>>

  note bottom of U6
    Система задает уточняющие
    вопросы при недостатке
    контекста для принятия решения
  end note

  note right of O1
    Пользователь получает
    структурированный ответ
    с указанием пути поиска
  end note
}
@enduml