services: 
  neo4j:
    image: neo4j:4.4-enterprise
    container_name: "neo4j"
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:7474/ || exit 1
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 10s
    volumes:
      - ${NEO4J_VOLUME_PATH}/data:/data
      - ${NEO4J_VOLUME_PATH}/var/lib/neo4j/conf:/var/lib/neo4j/conf
      - ${NEO4J_VOLUME_PATH}/var/lib/neo4j/import:/var/lib/neo4j/import
      - ${NEO4J_VOLUME_PATH}/plugins:/plugins
