name: Build LaTeX Preview on PR

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - report/**

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        uses: xu-cheng/texlive-action@v2
        with:
          texlive_version: "2023"
          scheme: "full"
          run: |
            cd report
            latexmk -pdf -interaction=nonstopmode -output-directory=build diploma/diploma_report.tex || true
            latexmk -pdf -interaction=nonstopmode -output-directory=build diploma/diploma_report.tex || true
            ls build/*.pdf
            echo '----'
            ls 

      - name: Generate changelog
        run: |
          git log --pretty=format:"- %s" > CHANGES.md
          cat CHANGES.md

      - name: Delete old draft release if exists
        run: |
          gh release delete DRAFT --yes || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: DRAFT
          release_name: "DRAFT Version"
          body_path: CHANGES.md
          overwrite: true
          files: |  
            report/build/diploma_report.pdf
